export const techAlias: Record<string, string> = {
  threedsmax: "threedsmax",
  "3ds max": "threedsmax",
  "autodesk 3ds max": "threedsmax",
  "3dsmax": "threedsmax",
  aarch64: "aarch64",
  arm64: "aarch64",
  "arm architecture 64-bit": "aarch64",
  adonisjs: "adonisjs",
  adonis: "adonisjs",
  "adonis.js": "adonisjs",
  aftereffects: "aftereffects",
  "adobe after effects": "aftereffects",
  ae: "aftereffects",
  adobeaftereffects: "aftereffects",
  akka: "akka",
  "akka toolkit": "akka",
  "akka actors": "akka",
  "akka-framework": "akka",
  algolia: "algolia",
  "algolia search": "algolia",
  "algolia api": "algolia",
  alpinejs: "alpinejs",
  "alpine.js": "alpinejs",
  alpine: "alpinejs",
  amazonwebservices: "amazonwebservices",
  aws: "amazonwebservices",
  "amazon cloud": "amazonwebservices",
  anaconda: "anaconda",
  "anaconda python": "anaconda",
  "anaconda distribution": "anaconda",
  android: "android",
  "android os": "android",
  "google android": "android",
  androidstudio: "androidstudio",
  "android studio ide": "androidstudio",
  "google android studio": "androidstudio",
  angular: "angular",
  "angular framework": "angular",
  "angular.io": "angular",
  angularjs: "angularjs",
  "angularjs framework": "angularjs",
  "angular 1.x": "angularjs",
  angularmaterial: "angularmaterial",
  "angular material ui": "angularmaterial",
  "material for angular": "angularmaterial",
  ansible: "ansible",
  "ansible automation": "ansible",
  "ansible playbooks": "ansible",
  antdesign: "antdesign",
  "ant design ui": "antdesign",
  antd: "antdesign",
  apache: "apache",
  "apache http server": "apache",
  "apache foundation": "apache",
  "the apache software foundation": "apache",
  apacheairflow: "apacheairflow",
  airflow: "apacheairflow",
  "apache airflow dags": "apacheairflow",
  apachekafka: "apachekafka",
  kafka: "apachekafka",
  "apache kafka streams": "apachekafka",
  apachespark: "apachespark",
  spark: "apachespark",
  "apache spark mllib": "apachespark",
  apl: "apl",
  "apl programming language": "apl",
  "array programming language": "apl",
  "a programming language": "apl",
  appcelerator: "appcelerator",
  "appcelerator titanium": "appcelerator",
  "titanium sdk": "titaniumsdk",
  apple: "apple",
  "apple inc.": "apple",
  "apple ecosystem": "apple",
  appwrite: "appwrite",
  "appwrite backend": "appwrite",
  "appwrite api": "appwrite",
  archlinux: "archlinux",
  arch: "archlinux",
  "arch linux os": "archlinux",
  arduino: "arduino",
  "arduino board": "arduino",
  "arduino ide": "arduino",
  argocd: "argocd",
  "argo cd": "argocd",
  "argo continuous delivery": "argocd",
  astro: "astro",
  "astro framework": "astro",
  "astro.build": "astro",
  atom: "atom",
  "atom editor": "atom",
  "github atom": "atom",
  awk: "awk",
  "awk scripting": "awk",
  "awk command": "awk",
  "the awk programming language": "awk",
  axios: "axios",
  "axios http client": "axios",
  "axios.js": "axios",
  azure: "azure",
  "microsoft azure": "azure",
  "azure cloud": "azure",
  microsoftazure: "azure",
  azuredevops: "azuredevops",
  "azure devops services": "azuredevops",
  "azure pipelines": "azuredevops",
  "azure-devops": "azuredevops",
  azuresqldatabase: "azuresqldatabase",
  "azure sql": "azuresqldatabase",
  "azure managed database": "azuresqldatabase",
  "azure-sql-database": "azuresqldatabase",
  babel: "babel",
  "babel.js": "babel",
  "babel compiler": "babel",
  babeljs: "babel",
  backbonejs: "backbonejs",
  backbone: "backbonejs",
  "backbone.js": "backbonejs",
  ballerina: "ballerina",
  "ballerina language": "ballerina",
  "ballerina.io": "ballerina",
  bal: "ballerina",
  bamboo: "bamboo",
  "atlassian bamboo": "bamboo",
  "bamboo ci/cd": "bamboo",
  atlassianbamboo: "bamboo",
  bash: "bash",
  "bash shell": "bash",
  "bourne again shell": "bash",
  bourneagainshell: "bash",
  beats: "beats",
  "elastic beats": "beats",
  "beats by elastic": "beats",
  behance: "behance",
  "adobe behance": "behance",
  "behance portfolio": "behance",
  bitbucket: "bitbucket",
  "bitbucket cloud": "bitbucket",
  "bitbucket git": "bitbucket",
  atlassianbitbucket: "bitbucket",
  blazor: "blazor",
  "blazor webassembly": "blazor",
  "blazor server": "blazor",
  blender: "blender",
  "blender 3d": "blender",
  "blender foundation": "blender",
  bootstrap: "bootstrap",
  "bootstrap css": "bootstrap",
  "bootstrap framework": "bootstrap",
  bower: "bower",
  "bower package manager": "bower",
  "bower.js": "bower",
  browserstack: "browserstack",
  "browserstack testing": "browserstack",
  "browserstack cloud": "browserstack",
  bulma: "bulma",
  "bulma css": "bulma",
  "bulma framework": "bulma",
  bulmacss: "bulma",
  bun: "bun",
  "bun.js": "bun",
  "bun runtime": "bun",
  c: "c",
  "c programming": "c",
  "c language": "c",
  cairo: "cairo",
  "cairo graphics": "cairo",
  "cairo 2d library": "cairo",
  cairographics: "cairo",
  cakephp: "cakephp",
  "cakephp framework": "cakephp",
  "cake php": "cakephp",
  canva: "canva",
  "canva design": "canva",
  "canva online editor": "canva",
  capacitor: "capacitor",
  "capacitor.js": "capacitor",
  "ionic capacitor": "capacitor",
  capacitorjs: "capacitor",
  carbon: "carbon",
  "carbon design system": "carbon",
  "ibm carbon": "carbon",
  "carbon language": "carbon",
  cassandra: "cassandra",
  "apache cassandra": "cassandra",
  "cassandra db": "cassandra",
  centos: "centos",
  "centos linux": "centos",
  "centos stream": "centos",
  ceylon: "ceylon",
  "ceylon language": "ceylon",
  "ceylon jvm": "ceylon",
  eclipseceylon: "ceylon",
  ceylonlang: "ceylon",
  chrome: "chrome",
  "google chrome": "chrome",
  "chrome browser": "chrome",
  googlechrome: "chrome",
  circleci: "circleci",
  "circleci pipelines": "circleci",
  "circleci ci/cd": "circleci",
  clarity: "clarity",
  "vmware clarity": "clarity",
  "clarity design system": "clarity",
  "clarity-lang": "clarity",
  clion: "clion",
  "clion ide": "clion",
  "jetbrains clion": "clion",
  clojure: "clojure",
  "clojure language": "clojure",
  "clojure jvm": "clojure",
  clojurescript: "clojurescript",
  "clojurescript compiler": "clojurescript",
  "clojure for javascript": "clojurescript",
  cloudflare: "cloudflare",
  "cloudflare cdn": "cloudflare",
  "cloudflare security": "cloudflare",
  cloudflareworkers: "cloudflareworkers",
  "cloudflare workers": "cloudflareworkers",
  "cloudflare edge computing": "cloudflareworkers",
  cmake: "cmake",
  "cmake build system": "cmake",
  "cmake tool": "cmake",
  codeac: "codeac",
  "codeac.io": "codeac",
  "codeac static analysis": "codeac",
  codeacio: "codeac",
  codecov: "codecov",
  "codecov coverage": "codecov",
  "codecov.io": "codecov",
  codeigniter: "codeigniter",
  "codeigniter framework": "codeigniter",
  "codeigniter php": "codeigniter",
  codepen: "codepen",
  "codepen.io": "codepen",
  "codepen playground": "codepen",
  coffeescript: "coffeescript",
  "coffeescript language": "coffeescript",
  "coffeescript compiler": "coffeescript",
  composer: "composer",
  "composer php": "composer",
  "php dependency manager": "composer",
  confluence: "confluence",
  "atlassian confluence": "confluence",
  "confluence wiki": "confluence",
  atlassianconfluence: "confluence",
  consul: "consul",
  "hashicorp consul": "consul",
  "consul service mesh": "consul",
  contao: "contao",
  "contao cms": "contao",
  "contao open source": "contao",
  corejs: "corejs",
  "core-js": "corejs",
  "javascript polyfills": "corejs",
  "core.js": "corejs",
  cosmosdb: "cosmosdb",
  "azure cosmos db": "cosmosdb",
  "cosmosdb nosql": "cosmosdb",
  azurecosmosdb: "cosmosdb",
  couchbase: "couchbase",
  "couchbase database": "couchbase",
  "couchbase nosql": "couchbase",
  couchdb: "couchdb",
  "apache couchdb": "couchdb",
  "couchdb json database": "couchdb",
  apachecouchdb: "couchdb",
  cplusplus: "cplusplus",
  "c++": "cplusplus",
  "c plus plus": "cplusplus",
  cpp: "cplusplus",
  crystal: "crystal",
  "crystal language": "crystal",
  "crystal programming": "crystal",
  crystallang: "crystal",
  csharp: "csharp",
  "c#": "csharp",
  "c sharp language": "csharp",
  css3: "css3",
  "css 3": "css3",
  "cascading style sheets 3": "css3",
  cascadingstylesheets3: "css3",
  cucumber: "cucumber",
  "cucumber bdd": "cucumber",
  "cucumber testing": "cucumber",
  cucumberjs: "cucumber",
  cypressio: "cypressio",
  cypress: "cypressio",
  "cypress test automation": "cypressio",
  d3js: "d3js",
  "d3.js": "d3js",
  "data-driven documents": "d3js",
  dart: "dart",
  "dart language": "dart",
  "dart vm": "dart",
  googledart: "dart",
  datagrip: "datagrip",
  "jetbrains datagrip": "datagrip",
  "datagrip sql ide": "datagrip",
  dataspell: "dataspell",
  "jetbrains dataspell": "dataspell",
  "dataspell ai notebook": "dataspell",
  dbeaver: "dbeaver",
  "dbeaver database tool": "dbeaver",
  "dbeaver sql client": "dbeaver",
  debian: "debian",
  "debian linux": "debian",
  "debian os": "debian",
  denojs: "denojs",
  deno: "denojs",
  "deno javascript runtime": "denojs",
  devicon: "devicon",
  "devicon icons": "devicon",
  "devicon technology icons": "devicon",
  digitalocean: "digitalocean",
  "digitalocean cloud": "digitalocean",
  "digitalocean vps": "digitalocean",
  discordjs: "discordjs",
  "discord.js": "discordjs",
  "discord api for javascript": "discordjs",
  django: "django",
  "django framework": "django",
  "django python": "django",
  djangorest: "djangorest",
  "django rest framework": "djangorest",
  drf: "djangorest",
  docker: "docker",
  "docker containers": "docker",
  "docker engine": "docker",
  doctrine: "doctrine",
  "doctrine orm": "doctrine",
  "doctrine php": "doctrine",
  "dot-net": "dot-net",
  ".net framework": "dot-net",
  "microsoft .net": "dot-net",
  dotnet: "dot-net",
  ".net": "dot-net",
  dotnetcore: "dotnetcore",
  ".net core": "dotnetcore",
  "microsoft .net core": "dotnetcore",
  ".netcore": "dotnetcore",
  dreamweaver: "dreamweaver",
  "adobe dreamweaver": "dreamweaver",
  "dreamweaver web editor": "dreamweaver",
  dropwizard: "dropwizard",
  "dropwizard java": "dropwizard",
  "dropwizard framework": "dropwizard",
  drupal: "drupal",
  "drupal cms": "drupal",
  "drupal open source": "drupal",
  dynamodb: "dynamodb",
  "amazon dynamodb": "dynamodb",
  "dynamodb nosql": "dynamodb",
  eclipse: "eclipse",
  "eclipse ide": "eclipse",
  "eclipse foundation": "eclipse",
  ecto: "ecto",
  "ecto elixir": "ecto",
  "ecto database wrapper": "ecto",
  elasticsearch: "elasticsearch",
  "elastic search engine": "elasticsearch",
  electron: "electron",
  "electron.js": "electron",
  "electron framework": "electron",
  electronjs: "electron",
  eleventy: "eleventy",
  "11ty": "eleventy",
  "eleventy static site generator": "eleventy",
  elixir: "elixir",
  "elixir language": "elixir",
  "elixir beam": "elixir",
  elexirlang: "elixir",
  elm: "elm",
  "elm language": "elm",
  "elm functional programming": "elm",
  elmlang: "elm",
  emacs: "emacs",
  "gnu emacs": "emacs",
  "emacs text editor": "emacs",
  editingmacros: "emacs",
  embeddedc: "embeddedc",
  "embedded c": "embeddedc",
  "c for embedded systems": "embeddedc",
  ember: "ember",
  "ember.js": "ember",
  "ember framework": "ember",
  emberjs: "ember",
  envoy: "envoy",
  "envoy proxy": "envoy",
  "envoy service mesh": "envoy",
  envoyproxy: "envoy",
  erlang: "erlang",
  "erlang language": "erlang",
  "erlang otp": "erlang",
  eslint: "eslint",
  "eslint linter": "eslint",
  "eslint javascript": "eslint",
  express: "express",
  "express.js": "express",
  "express node.js": "express",
  expressjs: "express",
  facebook: "facebook",
  meta: "facebook",
  "facebook social network": "facebook",
  fastapi: "fastapi",
  "fastapi framework": "fastapi",
  "fastapi python": "fastapi",
  fastify: "fastify",
  "fastify.js": "fastify",
  "fastify node.js": "fastify",
  faunadb: "faunadb",
  "fauna cloud database": "faunadb",
  fauna: "faunadb",
  feathersjs: "feathersjs",
  "feathers.js": "feathersjs",
  "feathers api framework": "feathersjs",
  fedora: "fedora",
  "fedora linux": "fedora",
  "fedora os": "fedora",
  figma: "figma",
  "figma design": "figma",
  "figma ui tool": "figma",
  filezilla: "filezilla",
  "filezilla ftp": "filezilla",
  "filezilla client": "filezilla",
  firebase: "firebase",
  "google firebase": "firebase",
  "firebase backend": "firebase",
  firefox: "firefox",
  "mozilla firefox": "firefox",
  "firefox browser": "firefox",
  mozillafirefox: "firefox",
  flask: "flask",
  "flask python": "flask",
  "flask web framework": "flask",
  flutter: "flutter",
  "flutter sdk": "flutter",
  "google flutter": "flutter",
  fortran: "fortran",
  "fortran language": "fortran",
  "fortran programming": "fortran",
  foundation: "foundation",
  "foundation css": "foundation",
  "foundation framework": "foundation",
  framermotion: "framermotion",
  "framer motion": "framermotion",
  "framer.js": "framermotion",
  "framer-motion": "framermotion",
  framer: "framermotion",
  framework7: "framework7",
  "framework7.js": "framework7",
  "framework7 mobile ui": "framework7",
  fsharp: "fsharp",
  "f#": "fsharp",
  "f sharp language": "fsharp",
  gatling: "gatling",
  "gatling load testing": "gatling",
  "gatling performance tool": "gatling",
  gatsby: "gatsby",
  "gatsby.js": "gatsby",
  "gatsby static site generator": "gatsby",
  gatsbyjs: "gatsby",
  gazebo: "gazebo",
  "gazebo simulator": "gazebo",
  "gazebo robotics": "gazebo",
  gcc: "gcc",
  "gcc compiler": "gcc",
  "gnu compiler collection": "gcc",
  gnucompilercollection: "gcc",
  gentoo: "gentoo",
  "gentoo linux": "gentoo",
  "gentoo os": "gentoo",
  ghost: "ghost",
  "ghost cms": "ghost",
  "ghost blogging platform": "ghost",
  gimp: "gimp",
  "gimp editor": "gimp",
  "gnu image manipulation program": "gimp",
  git: "git",
  "git version control": "git",
  "git scm": "git",
  gitbook: "gitbook",
  "gitbook documentation": "gitbook",
  "gitbook writing platform": "gitbook",
  github: "github",
  "github repository": "github",
  "github version control": "github",
  githubactions: "githubactions",
  "github actions ci/cd": "githubactions",
  "github workflows": "githubactions",
  "github actions": "githubactions",
  githubcodespaces: "githubcodespaces",
  "github codespaces": "githubcodespaces",
  "codespaces cloud ide": "githubcodespaces",
  gitlab: "gitlab",
  "gitlab ci/cd": "gitlab",
  "gitlab devops": "gitlab",
  gitpod: "gitpod",
  "gitpod cloud ide": "gitpod",
  "gitpod online coding": "gitpod",
  "gitpod-io": "gitpod",
  gitter: "gitter",
  "gitter chat": "gitter",
  "gitter community": "gitter",
  go: "go",
  "go language": "go",
  golang: "go",
  godot: "godot",
  "godot engine": "godot",
  "godot game development": "godot",
  goland: "goland",
  "goland ide": "goland",
  "jetbrains goland": "goland",
  google: "google",
  "google inc.": "google",
  "google search": "google",
  googlecloud: "googlecloud",
  "google cloud platform": "googlecloud",
  gcp: "googlecloud",
  gradle: "gradle",
  "gradle build tool": "gradle",
  "gradle java": "gradle",
  apachegradle: "gradle",
  gradlebuildtool: "gradle",
  grafana: "grafana",
  "grafana monitoring": "grafana",
  "grafana dashboards": "grafana",
  grails: "grails",
  "grails framework": "grails",
  "grails groovy": "grails",
  graphql: "graphql",
  "graphql api": "graphql",
  "graphql query language": "graphql",
  groovy: "groovy",
  "groovy language": "groovy",
  "groovy jvm": "groovy",
  groovylang: "groovy",
  apachegroovy: "groovy",
  grpc: "grpc",
  "grpc protocol": "grpc",
  "grpc remote procedure call": "grpc",
  grpcio: "grpc",
  "google remote procedure call": "grpc",
  grunt: "grunt",
  "grunt.js": "grunt",
  "grunt task runner": "grunt",
  gruntjs: "grunt",
  gulp: "gulp",
  "gulp.js": "gulp",
  "gulp task runner": "gulp",
  gulpjs: "gulp",
  hadoop: "hadoop",
  "apache hadoop": "hadoop",
  "hadoop big data": "hadoop",
  handlebars: "handlebars",
  "handlebars.js": "handlebars",
  "handlebars templating": "handlebars",
  handlebarsjs: "handlebars",
  hardhat: "hardhat",
  "hardhat ethereum": "hardhat",
  "hardhat blockchain development": "hardhat",
  harvester: "harvester",
  "harvester hci": "harvester",
  "harvester cloud-native": "harvester",
  harvesterhci: "harvester",
  haskell: "haskell",
  "haskell language": "haskell",
  "haskell functional programming": "haskell",
  haxe: "haxe",
  "haxe language": "haxe",
  "haxe multi-platform": "haxe",
  helm: "helm",
  "helm kubernetes": "helm",
  "helm charts": "helm",
  heroku: "heroku",
  "heroku cloud": "heroku",
  "heroku paas": "heroku",
  hibernate: "hibernate",
  "hibernate orm": "hibernate",
  "hibernate java": "hibernate",
  homebrew: "homebrew",
  "homebrew package manager": "homebrew",
  brew: "homebrew",
  html5: "html5",
  "html 5": "html5",
  "hypertext markup language 5": "html5",
  hypertextmarkdownlanguage5: "html5",
  hugo: "hugo",
  "hugo static site generator": "hugo",
  "hugo framework": "hugo",
  gohugo: "hugo",
  ie10: "ie10",
  "internet explorer 10": "ie10",
  "ie 10": "ie10",
  internetexplorer10: "ie10",
  ifttt: "ifttt",
  "ifttt automation": "ifttt",
  "if this then that": "ifttt",
  ifthisthenthat: "ifttt",
  illustrator: "illustrator",
  "adobe illustrator": "illustrator",
  "illustrator vector graphics": "illustrator",
  adobeillustrator: "illustrator",
  influxdb: "influxdb",
  "influxdb time series": "influxdb",
  "influx database": "influxdb",
  inkscape: "inkscape",
  "inkscape vector": "inkscape",
  "inkscape graphics editor": "inkscape",
  insomnia: "insomnia",
  "insomnia api client": "insomnia",
  "insomnia rest testing": "insomnia",
  "insomnia rest client": "insomnia",
  intellij: "intellij",
  "intellij idea": "intellij",
  "jetbrains intellij": "intellij",
  intellijidea: "intellij",
  ionic: "ionic",
  "ionic framework": "ionic",
  "ionic mobile development": "ionic",
  jaegertracing: "jaegertracing",
  "jaeger tracing": "jaegertracing",
  "jaeger distributed tracing": "jaegertracing",
  jaeger: "jaegertracing",
  jamstack: "jamstack",
  "jamstack architecture": "jamstack",
  "javascript apis markup": "jamstack",
  jasmine: "jasmine",
  "jasmine testing": "jasmine",
  "jasmine javascript": "jasmine",
  jasminejs: "jasmine",
  java: "java",
  "java programming": "java",
  "java language": "java",
  javascript: "javascript",
  js: "javascript",
  ecmascript: "javascript",
  jeet: "jeet",
  "jeet grid": "jeet",
  "jeet css framework": "jeet",
  jekyll: "jekyll",
  "jekyll static site generator": "jekyll",
  "jekyll blogging": "jekyll",
  jestjs: "jest",
  jenkins: "jenkins",
  "jenkins ci/cd": "jenkins",
  "jenkins automation": "jenkins",
  hudson: "jenkins",
  jest: "jest",
  "jest testing": "jest",
  "jest javascript": "jest",
  jetbrains: "jetbrains",
  "jetbrains software": "jetbrains",
  "jetbrains tools": "jetbrains",
  intellijsoftware: "jetbrains",
  jetpackcompose: "jetpackcompose",
  "jetpack compose": "jetpackcompose",
  "android jetpack compose": "jetpackcompose",
  jira: "jira",
  "atlassian jira": "jira",
  "jira issue tracking": "jira",
  atlassianjira: "jira",
  jiraalign: "jiraalign",
  "jira align": "jiraalign",
  "atlassian jira align": "jiraalign",
  jquery: "jquery",
  "jquery library": "jquery",
  "jquery javascript": "jquery",
  jqueryjs: "jquery",
  json: "json",
  "json format": "json",
  "javascript object notation": "json",
  jule: "jule",
  "jule language": "jule",
  "jule programming": "jule",
  julelang: "jule",
  julia: "julia",
  "julia language": "julia",
  "julia programming": "julia",
  julialang: "julia",
  junit: "junit",
  "junit testing": "junit",
  "junit java": "junit",
  jupyter: "jupyter",
  "jupyter notebook": "jupyter",
  "jupyter lab": "jupyter",
  jupyternotebook: "jupyter",
  k3os: "k3os",
  "k3os kubernetes": "k3os",
  "k3os rancher": "k3os",
  k3s: "k3s",
  "k3s kubernetes": "k3s",
  "k3s lightweight kubernetes": "k3s",
  k6: "k6",
  "k6 performance testing": "k6",
  "k6 load testing": "k6",
  kaggle: "kaggle",
  "kaggle data science": "kaggle",
  "kaggle ai competitions": "kaggle",
  karatelabs: "karatelabs",
  "karate api testing": "karatelabs",
  "karate dsl": "karatelabs",
  karate: "karatelabs",
  karma: "karma",
  "karma test runner": "karma",
  "karma javascript": "karma",
  karmarunner: "karma",
  karmajs: "karma",
  kdeneon: "kdeneon",
  "kde neon linux": "kdeneon",
  "kde neon os": "kdeneon",
  keras: "keras",
  "keras deep learning": "keras",
  "keras ai": "keras",
  kibana: "kibana",
  "kibana analytics": "kibana",
  "kibana elasticsearch": "kibana",
  knexjs: "knexjs",
  "knex.js": "knexjs",
  "knex sql query builder": "knexjs",
  knockout: "knockout",
  "knockout.js": "knockout",
  "knockout mvvm": "knockout",
  knockoutjs: "knockout",
  kotlin: "kotlin",
  "kotlin language": "kotlin",
  "kotlin android": "kotlin",
  kotlinlang: "kotlin",
  krakenjs: "krakenjs",
  "kraken.js": "krakenjs",
  "kraken node.js": "krakenjs",
  kraken: "krakenjs",
  ktor: "ktor",
  "ktor framework": "ktor",
  "ktor kotlin": "ktor",
  kubernetes: "kubernetes",
  k8s: "kubernetes",
  labview: "labview",
  "labview ni": "labview",
  "labview engineering": "labview",
  laravel: "laravel",
  "laravel php": "laravel",
  "laravel framework": "laravel",
  latex: "tex",
  "latex document": "latex",
  "latex typesetting": "latex",
  less: "less",
  "less css": "less",
  "less stylesheet": "less",
  lesscss: "less",
  linkedin: "linkedin",
  "linkedin network": "linkedin",
  "linkedin business": "linkedin",
  linux: "linux",
  "linux os": "linux",
  "gnu/linux": "linux",
  liquibase: "liquibase",
  "liquibase database": "liquibase",
  "liquibase version control": "liquibase",
  livewire: "livewire",
  "livewire laravel": "livewire",
  "livewire php": "livewire",
  "laravel-livewire": "livewire",
  llvm: "llvm",
  "llvm compiler": "llvm",
  "llvm infrastructure": "llvm",
  "low level virtual machine": "llvm",
  lodash: "lodash",
  "lodash.js": "lodash",
  "lodash utility library": "lodash",
  logstash: "logstash",
  "logstash elastic": "logstash",
  "logstash data pipeline": "logstash",
  lua: "lua",
  "lua language": "lua",
  "lua scripting": "lua",
  lualang: "lua",
  lumen: "lumen",
  "lumen php": "lumen",
  "lumen microframework": "lumen",
  "laravel lumen": "lumen",
  "lumen laravel": "lumen",
  "laravel lumen framework": "lumen",
  "laravel.lumen": "lumen",
  magento: "magento",
  "magento commerce": "magento",
  "adobe magento": "magento",
  mariadb: "mariadb",
  "mariadb database": "mariadb",
  "mariadb sql": "mariadb",
  markdown: "markdown",
  "markdown language": "markdown",
  "md format": "markdown",
  md: "markdown",
  materializecss: "materializecss",
  materialize: "materializecss",
  "materialize css framework": "materializecss",
  "materialize-css": "materializecss",
  "materialize css": "materializecss",
  materialui: "materialui",
  mui: "materialui",
  "material-ui": "materialui",
  matlab: "matlab",
  "matlab software": "matlab",
  "matlab mathworks": "matlab",
  matplotlib: "matplotlib",
  "matplotlib python": "matplotlib",
  "matplotlib visualization": "matplotlib",
  maven: "maven",
  "apache maven": "maven",
  "maven build tool": "maven",
  apachemaven: "maven",
  mvn: "maven",
  maya: "maya",
  "autodesk maya": "maya",
  "maya 3d": "maya",
  meteor: "meteor",
  "meteor.js": "meteor",
  "meteor javascript": "meteor",
  meteorjs: "meteor",
  microsoftsqlserver: "microsoftsqlserver",
  "microsoft sql server": "microsoftsqlserver",
  "ms sql": "microsoftsqlserver",
  msql: "microsoftsqlserver",
  mssql: "microsoftsqlserver",
  minitab: "minitab",
  "minitab statistical software": "minitab",
  "minitab data analysis": "minitab",
  mithril: "mithril",
  "mithril.js": "mithril",
  "mithril framework": "mithril",
  mobx: "mobx",
  "mobx state management": "mobx",
  "mobx react": "mobx",
  mobxjs: "mobx",
  mocha: "mocha",
  "mocha.js": "mocha",
  "mocha testing": "mocha",
  modx: "modx",
  "modx cms": "modx",
  "modx revolution": "modx",
  moleculer: "moleculer",
  "moleculer microservices": "moleculer",
  "moleculer.js": "moleculer",
  moleculerjs: "moleculer",
  mongodb: "mongodb",
  "mongodb nosql": "mongodb",
  "mongodb database": "mongodb",
  mongoose: "mongoose",
  "mongoose.js": "mongoose",
  "mongoose odm": "mongoose",
  mongoosejs: "mongoose",
  moodle: "moodle",
  "moodle lms": "moodle",
  "moodle elearning": "moodle",
  msdos: "msdos",
  "ms-dos": "msdos",
  "microsoft dos": "msdos",
  microsoftdiskoperatingsystem: "msdos",
  mysql: "mysql",
  "mysql database": "mysql",
  "mysql rdbms": "mysql",
  mystructuredquerylanguage: "mysql",
  nano: "nano",
  "gnu nano": "nano",
  "nano text editor": "nano",
  "gnu-nano": "nano",
  neo4j: "neo4j",
  "neo4j graph database": "neo4j",
  "neo4j nosql": "neo4j",
  neovim: "neovim",
  "neovim editor": "neovim",
  "neovim vim fork": "neovim",
  nestjs: "nestjs",
  "nest.js": "nestjs",
  "nestjs framework": "nestjs",
  netlify: "netlify",
  "netlify hosting": "netlify",
  "netlify jamstack": "netlify",
  networkx: "networkx",
  "networkx python": "networkx",
  "networkx graph library": "networkx",
  next: "nextjs",
  nextjs: "nextjs",
  "next.js": "nextjs",
  "next react framework": "nextjs",
  nginx: "nginx",
  "nginx server": "nginx",
  "nginx reverse proxy": "nginx",
  ngrx: "ngrx",
  "ngrx state management": "ngrx",
  "ngrx store": "ngrx",
  nhibernate: "nhibernate",
  "nhibernate orm": "nhibernate",
  ".net nhibernate": "nhibernate",
  nim: "nim",
  "nim language": "nim",
  "nim programming": "nim",
  nimlang: "nim",
  nimble: "nimble",
  "nimble package manager": "nimble",
  "nimble nim": "nimble",
  nixos: "nixos",
  "nixos linux": "nixos",
  "nixos os": "nixos",
  nodejs: "nodejs",
  "node.js": "nodejs",
  "node javascript runtime": "nodejs",
  nodemon: "nodemon",
  "nodemon auto-restart": "nodemon",
  "nodemon node.js": "nodemon",
  nodemonjs: "nodemon",
  nodewebkit: "nodewebkit",
  "nw.js": "nodewebkit",
  "node-webkit": "nodewebkit",
  nwjs: "nodewebkit",
  nomad: "nomad",
  "nomad hashicorp": "nomad",
  "nomad scheduler": "nomad",
  "hashicorp nomad": "nomad",
  norg: "norg",
  "norg markup": "norg",
  "norg notes": "norg",
  neorg: "norg",
  notion: "notion",
  "notion app": "notion",
  "notion productivity": "notion",
  npm: "npm",
  "node package manager": "npm",
  "npm.js": "npm",
  npmjs: "npm",
  nodepackagemanager: "npm",
  nuget: "nuget",
  "nuget .net": "nuget",
  "nuget package manager": "nuget",
  numpy: "numpy",
  "numpy python": "numpy",
  "numpy library": "numpy",
  nuxtjs: "nuxtjs",
  "nuxt.js": "nuxtjs",
  "nuxt vue framework": "nuxtjs",
  oauth: "oauth",
  "oauth authentication": "oauth",
  "oauth 2.0": "oauth",
  objectivec: "objectivec",
  "objective-c": "objectivec",
  "obj-c language": "objectivec",
  ocaml: "ocaml",
  "ocaml language": "ocaml",
  "ocaml programming": "ocaml",
  ohmyzsh: "ohmyzsh",
  "oh my zsh": "ohmyzsh",
  "zsh framework": "ohmyzsh",
  omz: "ohmyzsh",
  "ohmyz.sh": "ohmyzsh",
  okta: "okta",
  "okta identity": "okta",
  "okta authentication": "okta",
  "okta developer": "okta",
  openal: "openal",
  "openal audio": "openal",
  "open audio library": "openal",
  openapi: "openapi",
  "openapi specification": "openapi",
  "swagger api": "swagger",
  opencl: "opencl",
  "opencl computing": "opencl",
  "opencl gpu": "opencl",
  opencv: "opencv",
  "opencv computer vision": "opencv",
  "opencv ai": "opencv",
  opengl: "opengl",
  "opengl graphics": "opengl",
  "open graphics library": "opengl",
  opengraphicslibrary: "opengl",
  openstack: "openstack",
  "openstack cloud": "openstack",
  "openstack infrastructure": "openstack",
  opensuse: "opensuse",
  "opensuse linux": "opensuse",
  "opensuse os": "opensuse",
  opentelemetry: "opentelemetry",
  "opentelemetry observability": "opentelemetry",
  otel: "opentelemetry",
  opera: "opera",
  "opera browser": "opera",
  "opera web": "opera",
  oracle: "oracle",
  "oracle database": "oracle",
  "oracle db": "oracle",
  oracledatabase: "oracle",
  ory: "ory",
  "ory identity": "ory",
  "ory security": "ory",
  p5js: "p5js",
  "p5.js": "p5js",
  "processing p5.js": "p5js",
  packer: "packer",
  "packer hashicorp": "packer",
  "packer image builder": "packer",
  pandas: "pandas",
  "pandas python": "pandas",
  "pandas data analysis": "pandas",
  perl: "perl",
  "perl language": "perl",
  "perl programming": "perl",
  pfsense: "pfsense",
  "pfsense firewall": "pfsense",
  "pfsense router": "pfsense",
  phalcon: "phalcon",
  "phalcon php": "phalcon",
  "phalcon framework": "phalcon",
  phoenix: "phoenix",
  "phoenix framework": "phoenix",
  "phoenix elixir": "phoenix",
  photonengine: "photonengine",
  "photon engine": "photonengine",
  "photon multiplayer": "photonengine",
  photon: "photonengine",
  photoshop: "photoshop",
  "adobe photoshop": "photoshop",
  "photoshop cc": "photoshop",
  adobephotoshop: "photoshop",
  php: "php",
  "php language": "php",
  "php programming": "php",
  "php hypertext preprocessor": "php",
  "personal home page": "php",
  phpstorm: "phpstorm",
  "phpstorm ide": "phpstorm",
  "jetbrains phpstorm": "phpstorm",
  playwright: "playwright",
  "playwright testing": "playwright",
  "playwright automation": "playwright",
  plotly: "plotly",
  "plotly python": "plotly",
  "plotly.js": "plotly",
  pnpm: "pnpm",
  "pnpm package manager": "pnpm",
  "pnpm node.js": "pnpm",
  "performant npm": "pnpm",
  podman: "podman",
  "podman containers": "podman",
  "podman cli": "podman",
  poetry: "poetry",
  "poetry python": "poetry",
  "python dependency manager": "poetry",
  "python-poetry": "poetry",
  polygon: "polygon",
  "polygon blockchain": "polygon",
  "matic network": "polygon",
  portainer: "portainer",
  "portainer docker": "portainer",
  "portainer kubernetes": "portainer",
  postcss: "postcss",
  "postcss css processing": "postcss",
  postgresql: "postgresql",
  "postgres database": "postgresql",
  postman: "postman",
  "postman api testing": "postman",
  "postman client": "postman",
  powershell: "powershell",
  "powershell scripting": "powershell",
  "microsoft powershell": "powershell",
  ps: "powershell",
  premierepro: "premierepro",
  "adobe premiere pro": "premierepro",
  "premiere pro video editing": "premierepro",
  adobepremierepro: "premierepro",
  prisma: "prisma",
  "prisma orm": "prisma",
  "prisma database": "prisma",
  processing: "processing",
  "processing.js": "processing",
  "processing visualization": "processing",
  processingpy: "processing",
  prolog: "prolog",
  "prolog language": "prolog",
  "prolog ai": "prolog",
  "swi-prolog": "prolog",
  prometheus: "prometheus",
  "prometheus monitoring": "prometheus",
  "prometheus metrics": "prometheus",
  protractor: "protractor",
  "protractor testing": "protractor",
  "protractor angular": "protractor",
  protractorjs: "protractor",
  protractortest: "protractor",
  pulsar: "pulsar",
  "apache pulsar": "pulsar",
  "pulsar messaging": "pulsar",
  "pulsar edit": "pulsar",
  pulumi: "pulumi",
  "pulumi cloud infrastructure": "pulumi",
  "pulumi iac": "pulumi",
  puppeteer: "puppeteer",
  "puppeteer.js": "puppeteer",
  "puppeteer web automation": "puppeteer",
  purescript: "purescript",
  "purescript language": "purescript",
  "purescript fp": "purescript",
  putty: "putty",
  "putty ssh client": "putty",
  "putty terminal": "putty",
  pycharm: "pycharm",
  "pycharm ide": "pycharm",
  "jetbrains pycharm": "pycharm",
  pypi: "pypi",
  "pypi python": "pypi",
  "python package index": "pypi",
  pyscript: "pyscript",
  "pyscript python": "pyscript",
  "pyscript html": "pyscript",
  pytest: "pytest",
  "pytest python": "pytest",
  "pytest testing": "pytest",
  python: "python",
  "python language": "python",
  "python programming": "python",
  pytorch: "pytorch",
  "pytorch ai": "pytorch",
  "pytorch deep learning": "pytorch",
  qodana: "qodana",
  "qodana jetbrains": "qodana",
  "qodana code quality": "qodana",
  qt: "qt",
  "qt framework": "qt",
  "qt c++": "qt",
  quarkus: "quarkus",
  "quarkus java": "quarkus",
  "quarkus kubernetes": "quarkus",
  quasar: "quasar",
  "quasar framework": "quasar",
  "quasar vue.js": "quasar",
  qwik: "qwik",
  "qwik framework": "qwik",
  "qwik javascript": "qwik",
  r: "r",
  "r language": "r",
  "r programming": "r",
  rlang: "r",
  rabbitmq: "rabbitmq",
  "rabbitmq messaging": "rabbitmq",
  "rabbitmq broker": "rabbitmq",
  rails: "rails",
  "ruby on rails": "rails",
  "rails framework": "rails",
  rubyonrails: "rails",
  railway: "railway",
  "railway cloud": "railway",
  "railway app": "railway",
  rancher: "rancher",
  "rancher kubernetes": "rancher",
  "rancher cloud": "rancher",
  raspberrypi: "raspberrypi",
  "raspberry pi": "raspberrypi",
  "raspberry pi sbc": "raspberrypi",
  rpi: "raspberrypi",
  reach: "reach",
  "reach ui": "reach",
  "reach accessibility": "reach",
  "reach lang": "reach",
  react: "react",
  "react.js": "react",
  "react javascript": "react",
  reactjs: "react",
  reactbootstrap: "reactbootstrap",
  "react bootstrap": "reactbootstrap",
  "bootstrap react": "reactbootstrap",
  "react-bootstrap": "reactbootstrap",
  reactnavigation: "reactnavigation",
  "react navigation": "reactrouter",
  "react router navigation": "reactnavigation",
  readthedocs: "readthedocs",
  "read the docs": "readthedocs",
  "rtd documentation": "readthedocs",
  realm: "realm",
  "realm database": "realm",
  "mongodb realm": "realm",
  rect: "rect",
  "rect geometry": "rect",
  "rect js": "rect",
  rectlang: "rect",
  redhat: "redhat",
  "red hat linux": "redhat",
  rhel: "redhat",
  redis: "redis",
  "redis database": "redis",
  "redis cache": "redis",
  remotedictionaryserver: "redis",
  redux: "redux",
  "redux state management": "redux",
  "redux.js": "redux",
  reduxjs: "redux",
  renpy: "renpy",
  "ren'py visual novel": "renpy",
  "renpy python": "renpy",
  "ren'py": "renpy",
  replit: "replit",
  "replit cloud ide": "replit",
  "replit coding": "replit",
  rider: "rider",
  "jetbrains rider": "rider",
  "rider .net ide": "rider",
  rocksdb: "rocksdb",
  "rocksdb nosql": "rocksdb",
  "rocksdb database": "rocksdb",
  rockylinux: "rockylinux",
  "rocky linux": "rockylinux",
  "rocky os": "rockylinux",
  rocky: "rockylinux",
  rollup: "rollup",
  "rollup.js": "rollup",
  "rollup bundler": "rollup",
  rollupjs: "rollup",
  ros: "ros",
  "robot operating system": "ros",
  "ros robotics": "ros",
  robotoperatingsystem: "ros",
  rspec: "rspec",
  "rspec testing": "rspec",
  "rspec ruby": "rspec",
  rstudio: "rstudio",
  "rstudio ide": "rstudio",
  "rstudio analytics": "rstudio",
  ruby: "ruby",
  "ruby language": "ruby",
  "ruby programming": "ruby",
  rubylang: "ruby",
  rubymine: "rubymine",
  "rubymine ide": "rubymine",
  "jetbrains rubymine": "rubymine",
  rust: "rust",
  "rust language": "rust",
  "rust programming": "rust",
  rustlang: "rust",
  rxjs: "rxjs",
  "rxjs observables": "rxjs",
  "rxjs reactive programming": "rxjs",
  "reactive extensions for javascript": "rxjs",
  safari: "safari",
  "safari browser": "safari",
  "apple safari": "safari",
  applesafari: "safari",
  salesforce: "salesforce",
  "salesforce crm": "salesforce",
  "salesforce cloud": "salesforce",
  sanity: "sanity",
  "sanity cms": "sanity",
  "sanity.io": "sanity",
  sass: "sass",
  "sass css": "sass",
  "syntactically awesome stylesheets": "sass",
  scss: "sass",
  scala: "scala",
  "scala language": "scala",
  "scala jvm": "scala",
  scalalang: "scala",
  scalingo: "scalingo",
  "scalingo cloud": "scalingo",
  "scalingo paas": "scalingo",
  scikitlearn: "scikitlearn",
  "scikit-learn": "scikitlearn",
  "sklearn machine learning": "scikitlearn",
  scikit: "scikitlearn",
  sklearn: "scikitlearn",
  sdl: "sdl",
  "sdl library": "sdl",
  "simple directmedia layer": "sdl",
  simpledirectmedialayer: "sdl",
  selenium: "selenium",
  "selenium webdriver": "selenium",
  "selenium testing": "selenium",
  sema: "sema",
  "sema code review": "sema",
  "sema developer tools": "sema",
  "sema software": "sema",
  sentry: "sentry",
  "sentry error tracking": "sentry",
  "sentry monitoring": "sentry",
  reactrouter: "reactrouter",
  "react router": "reactrouter",
  sequelize: "sequelize",
  "sequelize orm": "sequelize",
  "sequelize node.js": "sequelize",
  sequelizejs: "sequelize",
  shopware: "shopware",
  "shopware cms": "shopware",
  "shopware ecommerce": "shopware",
  shotgrid: "shotgrid",
  "shotgrid autodesk": "shotgrid",
  "shotgrid production": "shotgrid",
  sketch: "sketch",
  "sketch design": "sketch",
  "sketch app": "sketch",
  slack: "slack",
  "slack messaging": "slack",
  "slack collaboration": "slack",
  socketio: "socketio",
  "socket.io": "socketio",
  "socket.io realtime": "socketio",
  solidity: "solidity",
  "solidity smart contracts": "solidity",
  "ethereum solidity": "solidity",
  soliditylang: "solidity",
  solidjs: "solidjs",
  "solid.js": "solidjs",
  "solid javascript framework": "solidjs",
  sonarqube: "sonarqube",
  "sonarqube code quality": "sonarqube",
  "sonarqube static analysis": "sonarqube",
  sonar: "sonarqube",
  sourcetree: "sourcetree",
  "sourcetree git": "sourcetree",
  "sourcetree atlassian": "sourcetree",
  spack: "spack",
  "spack package manager": "spack",
  "spack hpc": "spack",
  splunk: "splunk",
  "splunk monitoring": "splunk",
  "splunk data analysis": "splunk",
  spring: "spring",
  "spring framework": "spring",
  "spring java": "spring",
  springframework: "spring",
  spss: "spss",
  "spss statistics": "spss",
  "ibm spss": "spss",
  ibmspss: "spss",
  spyder: "spyder",
  "spyder ide": "spyder",
  "spyder python": "spyder",
  sqlalchemy: "sqlalchemy",
  "sqlalchemy orm": "sqlalchemy",
  "sqlalchemy python": "sqlalchemy",
  sqldeveloper: "sqldeveloper",
  "sql developer": "sqldeveloper",
  "oracle sql developer": "sqldeveloper",
  sqlite: "sqlite",
  "sqlite database": "sqlite",
  sqlite3: "sqlite",
  ssh: "ssh",
  "ssh protocol": "ssh",
  "secure shell": "ssh",
  secureshell: "ssh",
  stackoverflow: "stackoverflow",
  "stack overflow": "stackoverflow",
  "stackoverflow q&a": "stackoverflow",
  stata: "stata",
  "stata software": "stata",
  "stata data analysis": "stata",
  storybook: "storybook",
  "storybook ui": "storybook",
  "storybook.js": "storybook",
  storybookjs: "storybook",
  streamlit: "streamlit",
  "streamlit python": "streamlit",
  "streamlit dashboard": "streamlit",
  stylus: "stylus",
  "stylus css": "stylus",
  "stylus preprocessor": "stylus",
  styluslang: "stylus",
  subversion: "subversion",
  "apache subversion": "subversion",
  "svn version control": "subversion",
  apachesubversion: "subversion",
  supabase: "supabase",
  "supabase firebase alternative": "supabase",
  "supabase database": "supabase",
  svelte: "svelte",
  "svelte.js": "svelte",
  "svelte framework": "svelte",
  sveltejs: "svelte",
  swagger: "swagger",
  "swagger openapi": "swagger",
  swift: "swift",
  "swift language": "swift",
  "swift apple": "swift",
  swiper: "swiper",
  "swiper.js": "swiper",
  "swiper carousel": "swiper",
  symfony: "symfony",
  "symfony php": "symfony",
  "symfony framework": "symfony",
  tailwindcss: "tailwindcss",
  "tailwind css": "tailwindcss",
  "tailwind utility-first css": "tailwindcss",
  tauri: "tauri",
  "tauri framework": "tauri",
  "tauri rust": "tauri",
  tensorflow: "tensorflow",
  "tensorflow ai": "tensorflow",
  "tensorflow machine learning": "tensorflow",
  terraform: "terraform",
  "terraform iac": "terraform",
  "hashicorp terraform": "terraform",
  tex: "tex",
  "tex typesetting": "tex",
  thealgorithms: "thealgorithms",
  "the algorithms repo": "thealgorithms",
  "the algorithms open source": "thealgorithms",
  threejs: "threejs",
  "three.js": "threejs",
  "three.js webgl": "threejs",
  titaniumsdk: "titaniumsdk",
  "titanium appcelerator": "titaniumsdk",
  tomcat: "tomcat",
  "apache tomcat": "tomcat",
  "tomcat server": "tomcat",
  tortoisegit: "tortoisegit",
  "tortoisegit client": "tortoisegit",
  "tortoisegit gui": "tortoisegit",
  towergit: "towergit",
  "tower git client": "towergit",
  "tower git gui": "towergit",
  towergitclient: "towergit",
  traefikmesh: "traefikmesh",
  "traefik mesh": "traefikmesh",
  "traefik service mesh": "traefikmesh",
  traefikproxy: "traefikproxy",
  "traefik proxy": "traefikproxy",
  "traefik reverse proxy": "traefikproxy",
  travis: "travis",
  "travis ci": "travis",
  "travis continuous integration": "travis",
  travisci: "travis",
  trello: "trello",
  "trello boards": "trello",
  "trello kanban": "trello",
  atlassiantrello: "trello",
  trpc: "trpc",
  "trpc typescript": "trpc",
  "trpc framework": "trpc",
  "typescript remote procedure call": "trpc",
  twitter: "twitter",
  "twitter x": "twitter",
  "twitter social media": "twitter",
  x: "twitter",
  typescript: "typescript",
  "typescript language": "typescript",
  "ts javascript": "typescript",
  ts: "typescript",
  typo3: "typo3",
  "typo3 cms": "typo3",
  "typo3 open source": "typo3",
  ubuntu: "ubuntu",
  "ubuntu linux": "ubuntu",
  "ubuntu os": "ubuntu",
  unifiedmodelinglanguage: "unifiedmodelinglanguage",
  uml: "unifiedmodelinglanguage",
  "unified modeling language": "unifiedmodelinglanguage",
  unity: "unity",
  "unity engine": "unity",
  "unity game development": "unity",
  unix: "unix",
  "unix os": "unix",
  "unix operating system": "unix",
  unrealengine: "unrealengine",
  "unreal engine": "unrealengine",
  "unreal game engine": "unrealengine",
  uwsgi: "uwsgi",
  "uwsgi server": "uwsgi",
  "uwsgi python": "uwsgi",
  uwebservergatewayinterface: "uwsgi",
  v8: "v8",
  "v8 javascript engine": "v8",
  "google v8": "v8",
  "v8 engine": "v8",
  vagrant: "vagrant",
  "vagrant virtualization": "vagrant",
  "vagrant hashicorp": "vagrant",
  vala: "vala",
  "vala language": "vala",
  "vala programming": "vala",
  vault: "vault",
  "vault hashicorp": "vault",
  "vault secrets management": "vault",
  "hashicorp vault": "vault",
  vercel: "vercel",
  "vercel hosting": "vercel",
  "vercel next.js": "vercel",
  vertx: "vertx",
  "vert.x framework": "vertx",
  "eclipse vert.x": "vertx",
  eclipsevertx: "vertx",
  vim: "vim",
  "vim editor": "vim",
  "vi improved": "vim",
  viimproved: "vim",
  visualbasic: "visualbasic",
  "visual basic": "visualbasic",
  "vb.net": "visualbasic",
  vb: "visualbasic",
  visualstudio: "visualstudio",
  "visual studio ide": "visualstudio",
  "vs microsoft": "visualstudio",
  vs: "visualstudio",
  vite: "vitejs",
  "vite.js": "vitejs",
  "vite frontend tooling": "vite",
  vitejs: "vitejs",
  "vite.js framework": "vitejs",
  "vite webpack alternative": "vitejs",
  vitess: "vitess",
  "vitess database": "vitess",
  "vitess mysql scaling": "vitess",
  vitest: "vitest",
  "vitest testing": "vitest",
  "vitest vite": "vitest",
  vscode: "vscode",
  "vs code": "vscode",
  "visual studio code": "vscode",
  visualstudiocode: "vscode",
  vsphere: "vsphere",
  "vmware vsphere": "vsphere",
  "vsphere virtualization": "vsphere",
  vmwarevsphere: "vsphere",
  vuejs: "vuejs",
  "vue.js": "vuejs",
  "vue javascript framework": "vuejs",
  vuestorefront: "vuestorefront",
  "vue storefront": "vuestorefront",
  "vue ecommerce": "vuestorefront",
  vuetify: "vuetify",
  "vuetify ui": "vuetify",
  "vuetify vue": "vuetify",
  vyper: "vyper",
  "vyper smart contracts": "vyper",
  "vyper ethereum": "vyper",
  vyperlang: "vyper",
  wasm: "wasm",
  webassembly: "wasm",
  "wasm technology": "wasm",
  webflow: "webflow",
  "webflow cms": "webflow",
  "webflow website builder": "webflow",
  weblate: "weblate",
  "weblate translation": "weblate",
  "weblate localization": "weblate",
  webpack: "webpack",
  "webpack bundler": "webpack",
  "webpack javascript": "webpack",
  webpackjs: "webpack",
  webstorm: "webstorm",
  "webstorm ide": "webstorm",
  "jetbrains webstorm": "webstorm",
  windows11: "windows11",
  "windows 11 os": "windows11",
  "windows eleven": "windows11",
  windows8: "windows8",
  "windows 8 os": "windows8",
  "windows eight": "windows8",
  woocommerce: "woocommerce",
  "woocommerce plugin": "woocommerce",
  "woocommerce wordpress": "woocommerce",
  wordpress: "wordpress",
  "wordpress cms": "wordpress",
  "wp blogging": "wordpress",
  xamarin: "xamarin",
  "xamarin mobile": "xamarin",
  "xamarin .net": "xamarin",
  xcode: "xcode",
  "xcode ide": "xcode",
  "apple xcode": "xcode",
  xd: "xd",
  "adobe xd": "xd",
  "xd design tool": "xd",
  adobexd: "xd",
  xml: "xml",
  "xml markup": "xml",
  "extensible markup language": "xml",
  extensiblemarkuplanguage: "xml",
  yaml: "yaml",
  "yaml data format": "yaml",
  "yet another markup language": "yaml",
  "yaml ain't markup language": "yaml",
  yarn: "yarn",
  "yarn package manager": "yarn",
  "yarn javascript": "yarn",
  yii: "yii",
  "yii php": "yii",
  "yii framework": "yii",
  yesitis: "yii",
  yugabytedb: "yugabytedb",
  "yugabyte distributed sql": "yugabytedb",
  yunohost: "yunohost",
  "yunohost server": "yunohost",
  "yunohost self-hosting": "yunohost",
  zend: "zend",
  "zend framework": "zend",
  "zend php": "zend",
  zig: "zig",
  "zig language": "zig",
  "zig programming": "zig",
  ziglang: "zig",
};

export const techVersionsSvg: Record<string, string[]> = {
  threedsmax: ["original", "plain"],
  aarch64: ["original", "plain", "line"],
  adonisjs: ["original", "original-wordmark"],
  aftereffects: ["original", "plain"],
  akka: ["original", "original-wordmark"],
  algolia: ["original", "original-wordmark"],
  alpinejs: ["original", "original-wordmark"],
  amazonwebservices: ["original-wordmark", "plain-wordmark", "line-wordmark"],
  anaconda: ["original", "original-wordmark"],
  android: ["original", "original-wordmark", "plain", "plain-wordmark"],
  androidstudio: ["original", "original-wordmark", "plain", "plain-wordmark"],
  angular: ["original", "original-wordmark", "plain", "plain-wordmark"],
  angularjs: ["original", "original-wordmark", "plain", "plain-wordmark"],
  angularmaterial: ["original", "plain"],
  ansible: ["original", "original-wordmark", "plain", "plain-wordmark"],
  antdesign: ["original", "original-wordmark", "plain", "plain-wordmark"],
  apache: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  apacheairflow: ["original", "original-wordmark", "plain", "plain-wordmark"],
  apachekafka: ["original", "original-wordmark"],
  apachespark: ["original", "original-wordmark", "plain-wordmark"],
  apl: ["original", "plain"],
  appcelerator: ["original", "original-wordmark", "plain-wordmark"],
  apple: ["original"],
  appwrite: ["original", "original-wordmark", "plain", "plain-wordmark"],
  archlinux: ["original", "original-wordmark", "plain", "plain-wordmark"],
  arduino: ["original", "original-wordmark", "plain", "plain-wordmark"],
  argocd: ["original", "original-wordmark", "plain", "plain-wordmark"],
  astro: ["original", "original-wordmark", "plain", "plain-wordmark"],
  atom: ["original", "original-wordmark"],
  awk: ["original-wordmark", "plain-wordmark"],
  axios: ["plain", "plain-wordmark"],
  azure: ["original", "original-wordmark", "plain", "plain-wordmark"],
  azuredevops: ["original"],
  azuresqldatabase: ["original"],
  babel: ["original", "plain"],
  backbonejs: ["original", "original-wordmark", "plain", "plain-wordmark"],
  ballerina: ["original", "original-wordmark", "line", "line-wordmark"],
  bamboo: ["original", "original-wordmark"],
  bash: ["original", "plain"],
  beats: ["original"],
  behance: ["original", "original-wordmark", "plain", "plain-wordmark"],
  bitbucket: ["original", "original-wordmark"],
  blazor: ["original", "line"],
  blender: ["original", "original-wordmark"],
  bootstrap: ["original", "original-wordmark", "plain", "plain-wordmark"],
  bower: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  browserstack: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  bulma: ["plain"],
  bun: ["original", "plain", "line"],
  c: ["original", "plain", "line"],
  cairo: ["original", "plain", "original-wordmark", "plain-wordmark"],
  cakephp: ["original", "original-wordmark", "plain", "plain-wordmark"],
  canva: ["original"],
  capacitor: ["original", "original-wordmark", "plain", "plain-wordmark"],
  carbon: ["original"],
  cassandra: ["original", "original-wordmark", "plain", "plain-wordmark"],
  centos: ["original", "original-wordmark", "plain", "plain-wordmark"],
  ceylon: ["original", "original-wordmark", "plain", "plain-wordmark"],
  chrome: ["original", "original-wordmark", "plain", "plain-wordmark"],
  circleci: ["plain", "plain-wordmark"],
  clarity: ["original", "original-wordmark", "plain", "plain-wordmark"],
  clion: ["original", "original-wordmark", "plain", "plain-wordmark"],
  clojure: ["original", "line"],
  clojurescript: ["original", "plain"],
  cloudflare: ["original", "original-wordmark", "plain", "plain-wordmark"],
  cloudflareworkers: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
  ],
  cmake: ["original", "original-wordmark", "plain", "plain-wordmark"],
  codeac: ["original"],
  codecov: ["plain"],
  codeigniter: ["plain", "plain-wordmark"],
  codepen: ["original", "original-wordmark", "line", "line-wordmark"],
  coffeescript: ["original", "original-wordmark"],
  composer: ["original", "line", "line-wordmark"],
  confluence: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  consul: ["original", "original-wordmark", "plain-wordmark"],
  contao: ["original", "original-wordmark"],
  corejs: ["original", "original-wordmark"],
  cosmosdb: ["original", "original-wordmark"],
  couchbase: ["original", "original-wordmark", "plain-wordmark"],
  couchdb: ["original", "original-wordmark", "plain", "plain-wordmark"],
  cplusplus: ["original", "plain", "line"],
  crystal: ["original", "original-wordmark", "line", "line-wordmark"],
  csharp: ["original", "plain", "line"],
  css3: ["original", "original-wordmark", "plain", "plain-wordmark"],
  cucumber: ["plain", "plain-wordmark"],
  cypressio: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  d3js: ["original", "plain"],
  dart: ["original", "original-wordmark", "plain", "plain-wordmark"],
  datagrip: ["original", "plain", "plain-wordmark"],
  dataspell: ["original", "original-wordmark", "plain", "plain-wordmark"],
  dbeaver: ["original"],
  debian: ["original", "original-wordmark", "plain", "plain-wordmark"],
  denojs: ["original", "original-wordmark"],
  devicon: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  digitalocean: ["original", "original-wordmark"],
  discordjs: ["original", "original-wordmark", "plain", "plain-wordmark"],
  django: ["plain", "plain-wordmark"],
  djangorest: [
    "original",
    "plain",
    "line",
    "original-wordmark",
    "plain-wordmark",
    "line-wordmark",
  ],
  docker: ["original", "original-wordmark", "plain", "plain-wordmark"],
  doctrine: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  "dot-net": ["original", "original-wordmark", "plain", "plain-wordmark"],
  dotnetcore: ["original", "plain"],
  dreamweaver: ["original", "plain", "line"],
  dropwizard: ["original", "plain"],
  drupal: ["original", "original-wordmark", "plain", "plain-wordmark"],
  dynamodb: ["original", "plain"],
  eclipse: ["original", "original-wordmark"],
  ecto: ["original", "original-wordmark", "plain-wordmark"],
  elasticsearch: ["original", "original-wordmark", "plain", "plain-wordmark"],
  electron: ["original", "original-wordmark"],
  eleventy: ["original", "plain"],
  elixir: ["original", "original-wordmark", "plain", "plain-wordmark"],
  elm: ["original", "original-wordmark", "plain", "plain-wordmark"],
  emacs: ["original"],
  embeddedc: ["original", "original-wordmark", "plain", "plain-wordmark"],
  ember: ["original", "original-wordmark", "plain"],
  envoy: ["original", "original-wordmark"],
  erlang: ["original", "original-wordmark", "plain", "plain-wordmark"],
  eslint: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  express: ["original", "original-wordmark"],
  facebook: ["original", "plain"],
  fastapi: ["original", "original-wordmark", "plain", "plain-wordmark"],
  fastify: ["original", "original-wordmark", "plain", "plain-wordmark"],
  faunadb: ["original", "original-wordmark", "line", "line-wordmark"],
  feathersjs: ["original"],
  fedora: ["original", "plain"],
  figma: ["original", "plain"],
  filezilla: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  firebase: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  firefox: ["original", "original-wordmark", "plain", "plain-wordmark"],
  flask: ["original", "original-wordmark"],
  flutter: ["original", "plain"],
  fortran: ["original"],
  foundation: ["original", "original-wordmark", "plain", "plain-wordmark"],
  framermotion: ["original", "original-wordmark"],
  framework7: ["original", "original-wordmark"],
  fsharp: ["original", "plain"],
  gatling: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  gatsby: ["original", "original-wordmark", "plain-wordmark"],
  gazebo: ["original", "original-wordmark", "plain", "plain-wordmark"],
  gcc: ["original", "plain", "line"],
  gentoo: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  ghost: ["original", "original-wordmark"],
  gimp: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  git: ["original", "original-wordmark", "plain", "plain-wordmark"],
  gitbook: ["original", "original-wordmark", "line", "line-wordmark"],
  github: ["original", "original-wordmark"],
  githubactions: ["original", "plain"],
  githubcodespaces: ["original", "plain"],
  gitlab: ["original", "original-wordmark", "plain", "plain-wordmark"],
  gitpod: ["original", "original-wordmark", "plain", "plain-wordmark"],
  gitter: ["plain", "plain-wordmark"],
  go: ["original", "original-wordmark", "plain", "line"],
  godot: ["original", "original-wordmark", "plain", "plain-wordmark"],
  goland: ["original", "plain", "plain-wordmark"],
  google: ["original", "original-wordmark", "plain", "plain-wordmark"],
  googlecloud: ["original", "original-wordmark", "plain", "plain-wordmark"],
  gradle: ["original", "original-wordmark"],
  grafana: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  grails: ["original", "plain"],
  graphql: ["plain", "plain-wordmark"],
  groovy: ["original", "plain"],
  grpc: ["original", "plain"],
  grunt: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  gulp: ["plain"],
  hadoop: ["original", "original-wordmark", "plain", "plain-wordmark"],
  handlebars: ["original", "original-wordmark", "line", "line-wordmark"],
  hardhat: ["original", "original-wordmark", "plain", "plain-wordmark"],
  harvester: ["original", "original-wordmark", "plain-wordmark"],
  haskell: ["original", "original-wordmark", "plain", "plain-wordmark"],
  haxe: ["original", "plain"],
  helm: ["original", "line"],
  heroku: ["original", "original-wordmark", "plain", "plain-wordmark"],
  hibernate: ["original", "original-wordmark", "plain", "plain-wordmark"],
  homebrew: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  html5: ["original", "original-wordmark", "plain", "plain-wordmark"],
  hugo: ["original", "original-wordmark", "plain", "plain-wordmark"],
  ie10: ["original"],
  ifttt: ["original"],
  illustrator: ["plain", "line"],
  influxdb: ["original", "original-wordmark"],
  inkscape: ["original", "original-wordmark", "plain", "plain-wordmark"],
  insomnia: ["original", "original-wordmark", "plain", "plain-wordmark"],
  intellij: ["original", "plain", "plain-wordmark"],
  ionic: ["original", "original-wordmark"],
  jaegertracing: ["original", "original-wordmark", "plain", "plain-wordmark"],
  jamstack: ["original", "original-wordmark", "plain-wordmark"],
  jasmine: ["original", "original-wordmark"],
  java: ["original", "original-wordmark", "plain", "plain-wordmark"],
  javascript: ["original", "plain"],
  jeet: ["original", "original-wordmark", "plain", "plain-wordmark"],
  jekyll: ["original", "original-wordmark", "plain", "plain-wordmark"],
  jenkins: ["line", "original", "plain"],
  jest: ["plain"],
  jetbrains: ["original", "plain"],
  jetpackcompose: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  jira: ["original", "original-wordmark", "plain", "plain-wordmark"],
  jiraalign: ["original", "plain", "original-wordmark", "plain-wordmark"],
  jquery: ["original", "original-wordmark", "plain", "plain-wordmark"],
  json: ["original", "plain"],
  jule: ["original", "original-wordmark"],
  julia: ["original", "original-wordmark", "plain", "plain-wordmark"],
  junit: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  jupyter: ["original", "original-wordmark", "plain", "plain-wordmark"],
  k3os: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  k3s: ["original", "original-wordmark", "plain-wordmark"],
  k6: ["original"],
  kaggle: ["original", "original-wordmark"],
  karatelabs: ["original", "original-wordmark", "plain", "plain-wordmark"],
  karma: ["original", "plain"],
  kdeneon: ["original", "plain"],
  keras: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  kibana: ["original", "original-wordmark", "plain", "plain-wordmark"],
  knexjs: ["original", "original-wordmark", "plain-wordmark"],
  knockout: ["plain-wordmark"],
  kotlin: ["original", "original-wordmark", "plain", "plain-wordmark"],
  krakenjs: ["original", "original-wordmark", "plain", "plain-wordmark"],
  ktor: ["original", "original-wordmark", "plain", "plain-wordmark"],
  kubernetes: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  labview: ["original", "original-wordmark", "plain", "plain-wordmark"],
  laravel: ["original", "original-wordmark", "line", "line-wordmark"],
  latex: ["original"],
  less: ["plain-wordmark"],
  linkedin: ["original", "original-wordmark", "plain", "plain-wordmark"],
  linux: ["original", "plain"],
  liquibase: ["original", "original-wordmark"],
  livewire: ["original", "original-wordmark", "plain", "plain-wordmark"],
  llvm: ["original", "plain"],
  lodash: ["original", "plain"],
  logstash: ["original", "original-wordmark", "plain-wordmark", "plain"],
  lua: ["original", "plain", "line"],
  lumen: ["original"],
  magento: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  mariadb: ["original", "original-wordmark"],
  markdown: ["original"],
  materializecss: ["original", "plain"],
  materialui: ["original", "plain"],
  matlab: ["original", "plain", "line"],
  matplotlib: ["original", "original-wordmark", "plain", "plain-wordmark"],
  maven: ["original", "original-wordmark", "plain", "plain-wordmark"],
  maya: ["original", "original-wordmark", "plain", "plain-wordmark"],
  meteor: ["original", "original-wordmark", "plain", "plain-wordmark"],
  microsoftsqlserver: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  minitab: ["original", "plain"],
  mithril: ["original", "line"],
  mobx: ["original", "plain"],
  mocha: ["original", "plain"],
  modx: ["original", "original-wordmark", "plain", "plain-wordmark"],
  moleculer: ["original", "original-wordmark"],
  mongodb: ["original", "original-wordmark", "plain", "plain-wordmark"],
  mongoose: ["original", "original-wordmark"],
  moodle: ["original", "original-wordmark", "plain", "plain-wordmark"],
  msdos: ["original", "plain", "line"],
  mysql: ["original", "original-wordmark", "plain-wordmark"],
  nano: ["original", "original-wordmark", "plain", "plain-wordmark"],
  neo4j: ["original", "original-wordmark", "plain", "plain-wordmark"],
  neovim: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  nestjs: ["original", "original-wordmark", "line", "line-wordmark"],
  netlify: ["original", "original-wordmark", "plain", "plain-wordmark"],
  networkx: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  nextjs: ["original", "original-wordmark", "plain", "line", "line-wordmark"],
  nginx: ["original"],
  ngrx: ["original", "plain"],
  nhibernate: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "plain",
    "line",
    "line-wordmark",
  ],
  nim: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  nimble: ["original", "plain"],
  nixos: ["original", "original-wordmark", "plain", "plain-wordmark"],
  nodejs: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  nodemon: ["original", "plain", "line"],
  nodewebkit: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  nomad: ["original", "original-wordmark", "plain-wordmark"],
  norg: ["original", "plain"],
  notion: ["original", "plain", "line"],
  npm: ["original-wordmark"],
  nuget: ["original", "original-wordmark"],
  numpy: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  nuxtjs: ["original", "original-wordmark", "plain", "plain-wordmark"],
  oauth: ["original", "plain"],
  objectivec: ["plain"],
  ocaml: ["original", "original-wordmark", "plain", "plain-wordmark"],
  ohmyzsh: ["original", "plain"],
  okta: ["original", "original-wordmark", "plain", "plain-wordmark"],
  openal: ["original", "plain"],
  openapi: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  opencl: ["original", "plain", "line"],
  opencv: ["original", "original-wordmark", "plain", "plain-wordmark"],
  opengl: ["original", "plain"],
  openstack: ["original", "original-wordmark", "plain-wordmark"],
  opensuse: ["original", "original-wordmark"],
  opentelemetry: ["original", "original-wordmark", "plain", "plain-wordmark"],
  opera: ["original", "original-wordmark", "plain", "plain-wordmark"],
  oracle: ["original"],
  ory: ["original", "original-wordmark"],
  p5js: ["original"],
  packer: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  pandas: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  perl: ["original", "plain"],
  pfsense: ["original", "original-wordmark"],
  phalcon: ["original", "plain"],
  phoenix: ["original", "original-wordmark", "plain-wordmark"],
  photonengine: ["original", "plain"],
  photoshop: ["original", "plain", "line"],
  php: ["original", "plain"],
  phpstorm: ["original", "plain", "plain-wordmark"],
  playwright: ["original", "plain"],
  plotly: ["original", "original-wordmark", "plain", "plain-wordmark"],
  pnpm: ["original", "original-wordmark", "plain", "plain-wordmark"],
  podman: ["original", "original-wordmark", "plain", "plain-wordmark"],
  poetry: ["original"],
  polygon: ["original", "original-wordmark", "plain", "plain-wordmark"],
  portainer: ["original", "original-wordmark"],
  postcss: ["original", "original-wordmark", "plain-wordmark"],
  postgresql: ["original", "original-wordmark", "plain", "plain-wordmark"],
  postman: ["original", "original-wordmark", "plain", "plain-wordmark"],
  powershell: ["original", "plain"],
  premierepro: ["plain", "original"],
  prisma: ["original", "original-wordmark"],
  processing: ["original", "original-wordmark", "plain", "plain-wordmark"],
  prolog: ["original", "original-wordmark", "plain", "plain-wordmark"],
  prometheus: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  protractor: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  pulsar: ["original", "original-wordmark"],
  pulumi: ["original", "original-wordmark", "plain", "plain-wordmark"],
  puppeteer: ["original", "plain"],
  purescript: ["original", "original-wordmark"],
  putty: ["original", "plain"],
  pycharm: ["original", "original-wordmark", "plain", "plain-wordmark"],
  pypi: ["original", "original-wordmark", "plain", "plain-wordmark"],
  pyscript: ["original-wordmark", "plain-wordmark"],
  pytest: ["original", "original-wordmark", "plain", "plain-wordmark"],
  python: ["original", "original-wordmark", "plain", "plain-wordmark"],
  pytorch: ["original", "original-wordmark", "plain-wordmark"],
  qodana: ["original", "plain", "plain-wordmark"],
  qt: ["original"],
  quarkus: ["original", "original-wordmark", "plain", "plain-wordmark"],
  quasar: ["original", "original-wordmark", "plain", "plain-wordmark"],
  qwik: ["original", "original-wordmark", "plain", "plain-wordmark"],
  r: ["original", "plain", "line"],
  rabbitmq: ["original", "original-wordmark", "plain-wordmark"],
  rails: ["original-wordmark", "plain", "plain-wordmark"],
  railway: ["original", "original-wordmark", "line", "line-wordmark"],
  rancher: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  raspberrypi: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  reach: ["original", "plain"],
  react: ["original", "original-wordmark"],
  reactbootstrap: ["original"],
  reactnavigation: ["original"],
  readthedocs: ["original", "original-wordmark", "line"],
  realm: ["original", "original-wordmark", "plain", "plain-wordmark"],
  rect: ["original", "plain"],
  redhat: ["original", "original-wordmark", "plain", "plain-wordmark"],
  redis: ["original", "original-wordmark", "plain", "plain-wordmark"],
  redux: ["original"],
  renpy: ["original", "plain"],
  replit: ["original", "original-wordmark", "plain-wordmark"],
  rider: ["original", "original-wordmark", "plain", "plain-wordmark"],
  rocksdb: ["original", "plain", "line"],
  rockylinux: ["original", "original-wordmark", "plain-wordmark"],
  rollup: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  ros: ["original", "original-wordmark"],
  rspec: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  rstudio: ["original", "plain"],
  ruby: ["original", "original-wordmark", "plain", "plain-wordmark"],
  rubymine: ["original", "original-wordmark", "plain", "plain-wordmark"],
  rust: ["original", "line"],
  rxjs: ["original", "plain"],
  safari: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line-wordmark",
    "line",
  ],
  salesforce: ["original", "plain"],
  sanity: ["original", "plain"],
  sass: ["original"],
  scala: ["original", "original-wordmark", "plain", "plain-wordmark"],
  scalingo: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  scikitlearn: ["original", "plain", "line"],
  sdl: ["original", "plain"],
  selenium: ["original"],
  sema: ["original", "original-wordmark"],
  sentry: ["original", "original-wordmark"],
  reactrouter: ["original", "original-wordmark", "plain", "plain-wordmark"],
  sequelize: ["original", "original-wordmark", "plain", "plain-wordmark"],
  shopware: ["original", "original-wordmark"],
  shotgrid: ["original", "original-wordmark", "plain"],
  sketch: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  slack: ["original", "original-wordmark", "plain", "plain-wordmark"],
  socketio: ["original", "original-wordmark"],
  solidity: ["original", "plain"],
  solidjs: ["original", "original-wordmark", "plain", "plain-wordmark"],
  sonarqube: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  sourcetree: ["original", "original-wordmark"],
  spack: ["original", "plain"],
  splunk: ["original-wordmark"],
  spring: ["original", "original-wordmark"],
  spss: ["original", "plain"],
  spyder: ["original", "original-wordmark", "plain", "plain-wordmark"],
  sqlalchemy: ["original", "original-wordmark", "plain", "plain-wordmark"],
  sqldeveloper: ["original", "plain"],
  sqlite: ["original", "original-wordmark", "plain", "plain-wordmark"],
  ssh: ["original", "original-wordmark"],
  stackoverflow: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  stata: ["original-wordmark"],
  storybook: ["original", "original-wordmark", "plain", "plain-wordmark"],
  streamlit: ["original", "original-wordmark", "plain", "plain-wordmark"],
  stylus: ["original"],
  subversion: ["original", "original-wordmark", "plain-wordmark"],
  supabase: ["original", "original-wordmark", "plain", "plain-wordmark"],
  svelte: ["original", "original-wordmark", "plain", "plain-wordmark"],
  swagger: ["original", "original-wordmark", "plain", "plain-wordmark"],
  swift: ["original", "original-wordmark", "plain", "plain-wordmark"],
  swiper: ["original"],
  symfony: ["original", "original-wordmark"],
  tailwindcss: ["original", "original-wordmark", "plain-wordmark"],
  tauri: ["original", "original-wordmark", "plain", "plain-wordmark"],
  tensorflow: ["original", "original-wordmark", "line", "line-wordmark"],
  terraform: ["original", "original-wordmark", "plain", "plain-wordmark"],
  tex: ["original"],
  thealgorithms: ["original", "original-wordmark", "plain", "plain-wordmark"],
  threejs: ["original", "original-wordmark"],
  titaniumsdk: ["original"],
  tomcat: ["original", "original-wordmark", "line", "line-wordmark"],
  tortoisegit: ["original", "plain", "line"],
  towergit: ["original", "original-wordmark", "plain", "plain-wordmark"],
  traefikmesh: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  traefikproxy: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  travis: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  trello: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  trpc: ["original", "original-wordmark", "plain", "plain-wordmark"],
  twitter: ["original"],
  typescript: ["original", "plain"],
  typo3: [
    "original",
    "original-wordmark",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  ubuntu: ["original", "original-wordmark", "plain", "plain-wordmark"],
  unifiedmodelinglanguage: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
  ],
  unity: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  unix: ["original"],
  unrealengine: ["original", "original-wordmark"],
  uwsgi: ["original", "plain"],
  v8: ["original", "plain"],
  vagrant: ["original", "original-wordmark", "plain", "plain-wordmark"],
  vala: ["original", "original-wordmark", "plain", "plain-wordmark"],
  vault: ["original", "original-wordmark", "plain-wordmark"],
  vercel: ["original", "original-wordmark", "line", "line-wordmark"],
  vertx: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  vim: ["original", "plain"],
  visualbasic: ["original", "plain", "line"],
  visualstudio: ["original", "plain", "line"],
  vite: ["original", "original-wordmark"],
  vitejs: ["original", "plain"],
  vitess: ["original", "original-wordmark", "plain", "plain-wordmark"],
  vitest: ["original", "plain"],
  vscode: ["original", "original-wordmark", "plain", "plain-wordmark"],
  vsphere: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  vuejs: [
    "original",
    "original-wordmark",
    "plain",
    "plain-wordmark",
    "line",
    "line-wordmark",
  ],
  vuestorefront: ["original", "plain"],
  vuetify: ["original", "plain", "line"],
  vyper: ["original", "original-wordmark", "plain", "plain-wordmark"],
  wasm: ["original", "original-wordmark", "plain-wordmark"],
  webflow: ["original"],
  weblate: ["original", "plain", "original-wordmark", "plain-wordmark"],
  webpack: ["original", "original-wordmark", "plain", "plain-wordmark"],
  webstorm: ["original", "original-wordmark", "plain", "plain-wordmark"],
  windows11: ["original", "original-wordmark"],
  windows8: ["original", "original-wordmark"],
  woocommerce: ["original", "plain", "original-wordmark", "plain-wordmark"],
  wordpress: ["original", "plain", "plain-wordmark"],
  xamarin: ["original", "original-wordmark"],
  xcode: ["original", "plain"],
  xd: ["original", "plain", "line"],
  xml: ["original", "plain", "line"],
  yaml: ["original", "plain"],
  yarn: ["original", "original-wordmark", "line", "line-wordmark"],
  yii: ["original", "original-wordmark", "plain", "plain-wordmark"],
  yugabytedb: ["original", "original-wordmark", "plain", "plain-wordmark"],
  yunohost: ["original", "plain"],
  zend: ["original", "original-wordmark", "line", "line-wordmark"],
  zig: ["original", "original-wordmark", "plain-wordmark"],
};
